import { Dog } from "./type";

export const sampleDogs: Dog[] = [
  {
    id: "1",
    name: "Buddy",
    type: "Dog",
    breed: "Golden Retriever",
    age: 3,
    gender: "male",
    size: "large",
    intakeDate: "2025-07-15T10:00:00.000Z",
    description: "Friendly golden who loves playing fetch and swimming!",
    email: "radon123@gmail.com",
    phone: "9108697087",
    altPhone: "9108675849",
    country: "US",
    state: "OR",
    city: "Portland",
    zipCode: "97201",
    address: "123 Pet Shelter Lane",
    isVaccinated: true,
    isSpayedNeutered: true,
    isHouseTrained: true,
    goodWithChildren: true,
    goodWithDogs: true,
    goodWithCats: false,
    hasSpecialNeeds: false,
    specialNeedsDescription: "",
    medicalHistory: "Up to date on all vaccinations, no known health issues",
    tags: ["Friendly", "Playful", "Loyal"],
    photos: [
      { url: "/pets/goldenRetriver.jpg", alt: "Buddy the Golden Retriever" },
      { url: "/pets/goldenRetriver2.jpg", alt: "Buddy playing fetch" },
    ],
    featured: true,
  },
  {
    id: "2",
    name: "Luna",
    type: "Dog",
    breed: "Siberian Husky",
    age: 2,
    gender: "female",
    size: "medium",
    intakeDate: "2025-06-20T14:30:00.000Z",
    description: "Energetic husky who loves running and cold weather!",
    email: "radon123@gmail.com",
    phone: "9108697087",
    altPhone: "9108675849",
    country: "US",
    state: "WA",
    city: "Seattle",
    zipCode: "98101",
    address: "456 Rescue Road",
    isVaccinated: true,
    isSpayedNeutered: true,
    isHouseTrained: false,
    goodWithChildren: true,
    goodWithDogs: true,
    goodWithCats: false,
    hasSpecialNeeds: false,
    specialNeedsDescription: "",
    medicalHistory: "Healthy, needs more training",
    tags: ["Energetic", "Vocal", "Curious"],
    photos: [
      { url: "/pets/husky.jpg", alt: "Luna the Husky" },
      { url: "/pets/husky2.jpg", alt: "Luna in the snow" },
    ],
  },
  {
    id: "3",
    name: "Max",
    type: "Dog",
    breed: "Beagle",
    age: 4,
    gender: "male",
    size: "medium",
    intakeDate: "2025-05-10T09:15:00.000Z",
    description: "Curious beagle who loves following scents and cuddles!",
    email: "radon123@gmail.com",
    phone: "9108697087",
    altPhone: "9108675849",
    country: "US",
    state: "TX",
    city: "Austin",
    zipCode: "78701",
    address: "789 Adoption Avenue",
    isVaccinated: true,
    isSpayedNeutered: false,
    isHouseTrained: true,
    goodWithChildren: true,
    goodWithDogs: true,
    goodWithCats: true,
    hasSpecialNeeds: false,
    specialNeedsDescription: "",
    medicalHistory: "Healthy, all vaccinations current",
    tags: ["Curious", "Friendly", "Energetic"],
    photos: [
      { url: "/pets/beagle.jpg", alt: "Max the Beagle" },
      { url: "/pets/beagle2.jpg", alt: "Max sniffing flowers" },
    ],
  },
  {
    id: "4",
    name: "Bella",
    type: "Dog",
    breed: "French Bulldog",
    age: 3,
    gender: "female",
    size: "small",
    intakeDate: "2025-04-05T11:45:00.000Z",
    description: "Sweet lap dog who loves attention and short walks!",
    email: "radon123@gmail.com",
    phone: "9108697087",
    altPhone: "9108675849",
    country: "US",
    state: "FL",
    city: "Miami",
    zipCode: "33101",
    address: "321 Foster Street",
    isVaccinated: true,
    isSpayedNeutered: true,
    isHouseTrained: false,
    goodWithChildren: true,
    goodWithDogs: false,
    goodWithCats: true,
    hasSpecialNeeds: true,
    specialNeedsDescription:
      "Needs air conditioning in hot weather due to breathing sensitivity",
    medicalHistory: "Brachycephalic breed, needs climate control",
    tags: ["Affectionate", "Playful", "Loyal"],
    photos: [
      { url: "/pets/frenchBulldog.jpg", alt: "Bella the French Bulldog" },
      { url: "/pets/frenchBulldog2.jpg", alt: "Bella sleeping" },
    ],
  },
  {
    id: "5",
    name: "Rocky",
    type: "Dog",
    breed: "German Shepherd",
    age: 5,
    gender: "male",
    size: "large",
    intakeDate: "2025-03-12T13:20:00.000Z",
    description: "Protective companion perfect for an active family!",
    email: "radon123@gmail.com",
    phone: "9108697087",
    altPhone: "9108675849",
    country: "US",
    state: "CO",
    city: "Denver",
    zipCode: "80201",
    address: "654 Training Trail",
    isVaccinated: true,
    isSpayedNeutered: true,
    isHouseTrained: true,
    goodWithChildren: true,
    goodWithDogs: true,
    goodWithCats: false,
    hasSpecialNeeds: false,
    specialNeedsDescription: "",
    medicalHistory: "Former working dog, knows basic commands",
    tags: ["Loyal", "Protective", "Intelligent"],
    photos: [
      { url: "/pets/germanShepherd.jpg", alt: "Rocky the German Shepherd" },
      { url: "/pets/germanShepherd2.jpg", alt: "Rocky on patrol" },
    ],
  },
  {
    id: "6",
    name: "Molly",
    type: "Dog",
    breed: "Indie",
    age: 2,
    gender: "female",
    size: "medium",
    intakeDate: "2025-02-18T16:10:00.000Z",
    description: "Gentle soul who gets along with everyone!",
    email: "radon123@gmail.com",
    phone: "9108697087",
    altPhone: "9108675849",
    country: "US",
    state: "MA",
    city: "Boston",
    zipCode: "02101",
    address: "987 Companion Court",
    isVaccinated: true,
    isSpayedNeutered: true,
    isHouseTrained: true,
    goodWithChildren: true,
    goodWithDogs: true,
    goodWithCats: true,
    hasSpecialNeeds: false,
    specialNeedsDescription: "",
    medicalHistory: "Rescued from street, now fully healthy",
    tags: ["Gentle", "Affectionate", "Playful"],
    photos: [
      { url: "/pets/indie.jpg", alt: "Molly the Indie dog" },
      { url: "/pets/indie2.jpg", alt: "Molly playing" },
    ],
  },
];
